/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Task_5_gradle;

public class App {
    public String getGreeting() {
        return "Hello world! from Gradle";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
