/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Task_5_gradle;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testMainHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
